// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTSByuH7t3u3uhPQSDbs5dTPZY4v8_rn4',
    appId: '1:999521443229:web:689562a00ae35b20e22374',
    messagingSenderId: '999521443229',
    projectId: 'e-commerce-da34b',
    authDomain: 'e-commerce-da34b.firebaseapp.com',
    storageBucket: 'e-commerce-da34b.firebasestorage.app',
    measurementId: 'G-Z0L6BD9L7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB-2OqGRXBEqXr1_e1TohzM2wpWezBIyY',
    appId: '1:999521443229:android:5fd3f767b5f66783e22374',
    messagingSenderId: '999521443229',
    projectId: 'e-commerce-da34b',
    storageBucket: 'e-commerce-da34b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq-YgHOlreE-r7KE73qLzBezSkDo1ptN0',
    appId: '1:999521443229:ios:e3cda858288f1c28e22374',
    messagingSenderId: '999521443229',
    projectId: 'e-commerce-da34b',
    storageBucket: 'e-commerce-da34b.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq-YgHOlreE-r7KE73qLzBezSkDo1ptN0',
    appId: '1:999521443229:ios:e3cda858288f1c28e22374',
    messagingSenderId: '999521443229',
    projectId: 'e-commerce-da34b',
    storageBucket: 'e-commerce-da34b.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTSByuH7t3u3uhPQSDbs5dTPZY4v8_rn4',
    appId: '1:999521443229:web:e0f4c289f408a239e22374',
    messagingSenderId: '999521443229',
    projectId: 'e-commerce-da34b',
    authDomain: 'e-commerce-da34b.firebaseapp.com',
    storageBucket: 'e-commerce-da34b.firebasestorage.app',
    measurementId: 'G-0XNFX9KC8F',
  );
}
